### ISSUE TITLE
ToDo & Ideas

### ISSUE THREAD

**Issue by Naios** [Naios/fluent.cpp#1]
- [ ] Continuable::operator&& to support "and" chaining.
- [ ] Continuable::operator|| to support "or" chaining.
- [ ] Continuable<>::toFuture()
- [ ] Parameter pass through with evaluation.
- [ ] Fail handler (exceptions & error codes)
- [ ] Options to define strategies
